#!/usr/bin/env node
/**
 * consumer-census — fixtures for the generator `.claude/bin/census-build.mjs`.
 *
 * WHY THIS EXISTS AT ALL. `census-build.mjs` is a GATING check: `--check` exits 1 and a
 * `--codify`/CI lane can read that as a verdict. `instrument-bipolarity.md` MUST-1 says a
 * gating check ships an executable POLE PAIR run by the same harness, and MUST-2 says the RED
 * pole names a failure IDENTITY rather than a quantity. A generator shipped with no pole pair
 * is the unwired-instrument class the census it generates exists to end — one indirection out.
 *
 * BIPOLAR BY CONSTRUCTION. Every leg below is TWO cases that differ only in the thing the leg
 * is about. A generator shown only to refuse proves it can say "no"; it does not prove it can
 * say anything else, and a check that reds on everything is as useless as one that reds on
 * nothing.
 *
 * EXIT CODES ARE ASSERTED EXACTLY, never as "non-zero". `2` (UNRUNNABLE, refused, nothing
 * written) and `1` (STALE) mean opposite things — a dirty tree must not read as a stale block
 * — and a case accepting either cannot tell them apart. Each RED case additionally asserts a
 * SUBSTRING naming the failure kind, so a red produced by a DIFFERENT defect does not pass.
 *
 * REAL BINARY, REAL GIT REPO, NO MOCKS. Each case builds a temporary git repository, COPIES
 * the real generator into it (the tool resolves its repo from `import.meta.url`, so a copy is
 * what points it at the fixture) and invokes it as a subprocess. The copy is possible only
 * because the generator has ZERO RELATIVE IMPORTS — node builtins alone. Keep it that way.
 */
import "../_lib/no-ambient-git.cjs";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync, execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..", "..");
const TOOL_SRC = process.env.CENSUS_TOOL || path.join(REPO_ROOT, ".claude", "bin", "census-build.mjs");

let pass = 0;
const failures = [];

// `PASS <name>` at column 0 is the shape run-audit-fixtures.mjs::CASE_PASS counts.
function check(name, fn) {
  let ok;
  try {
    ok = fn();
  } catch (e) {
    ok = `threw: ${e && e.message}`;
  }
  if (ok === true) {
    pass++;
    console.log(`PASS ${name}`);
  } else {
    failures.push(name);
    console.log(`FAIL ${name}${typeof ok === "string" ? ` — ${ok}` : ""}`);
  }
}

// ── fixture repo construction ───────────────────────────────────────────────

const MANIFEST = {
  symbol: "deriveDynamicTokens",
  producer: "lib/producer.mjs",
  scan_globs: ["*.mjs"],
  target: "lib/producer.mjs",
  marker_id: "CONSUMER-CENSUS",
  indent: "  ",
};

const MARK_BEGIN =
  "  // CENSUS:BEGIN CONSUMER-CENSUS — generated by .claude/bin/census-build.mjs — DO NOT EDIT BY HAND";
const MARK_END = "  // CENSUS:END CONSUMER-CENSUS";

/** The producer: declares the symbol, carries the markers, returns three keys. */
function producer(keys = ["scrub", "gate", "unhonoured"]) {
  return [
    "export function deriveDynamicTokens(repoDir) {",
    "  const scrub = [], gate = [], unhonoured = [];",
    "  // judgment prose that must survive regeneration untouched",
    MARK_BEGIN,
    "  // (not yet generated)",
    MARK_END,
    "  // more judgment prose",
    `  return { ${keys.join(", ")} };`,
    "}",
    "",
  ].join("\n");
}

/** A consumer with a caller, so it is not dead. */
const CONSUMER_LIVE = [
  'import { deriveDynamicTokens } from "./lib/producer.mjs";',
  "export function liveLane(root) {",
  "  const { gate } = deriveDynamicTokens(root);",
  "  return gate.filter((t) => t.length >= 3);",
  "}",
  "export function driver(root) {",
  "  return liveLane(root);",
  "}",
  "",
].join("\n");

/** A consumer nothing calls — the dead-code pole. */
const CONSUMER_DEAD = [
  'import { deriveDynamicTokens } from "./lib/producer.mjs";',
  "export function orphanLane(root) {",
  "  const { scrub } = deriveDynamicTokens(root);",
  "  return scrub;",
  "}",
  "",
].join("\n");

/** Mentions the symbol only in PROSE — must contribute no row. */
const MENTION_ONLY = [
  "// This file talks about deriveDynamicTokens but never calls it.",
  "// `deriveDynamicTokens(root)` in backticks is documentation, not a call site.",
  "export const NOTE = 1;",
  "",
].join("\n");

function baseFiles(extra = {}) {
  return {
    "lib/producer.mjs": producer(),
    "consumer-live.mjs": CONSUMER_LIVE,
    "mention-only.mjs": MENTION_ONLY,
    "census-manifest.json": JSON.stringify(MANIFEST, null, 2) + "\n",
    ...extra,
  };
}

function mkRepo(files) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "census-fx-"));
  for (const [rel, body] of Object.entries(files)) {
    const abs = path.join(dir, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, body);
  }
  fs.mkdirSync(path.join(dir, ".claude", "bin"), { recursive: true });
  fs.copyFileSync(TOOL_SRC, path.join(dir, ".claude", "bin", "census-build.mjs"));
  // The tool routes every git spawn through the shared helper (1471-G7 ratchet over
  // `.claude/bin/**`: absolute binary + constants-built env). It resolves that helper RELATIVE TO
  // ITSELF, so a fixture that stages the binary without its dependency stages something that
  // cannot run — which is what happened the first time the ratchet was satisfied: 22/22 went red
  // at once, and the red was about the FIXTURE, not the tool. Staged here so the temp repo
  // reproduces the tool's real dependency rather than a convenient subset of it.
  const helperRel = path.join(".claude", "hooks", "lib", "git-subprocess-env.js");
  fs.mkdirSync(path.join(dir, ".claude", "hooks", "lib"), { recursive: true });
  fs.copyFileSync(path.join(REPO_ROOT, helperRel), path.join(dir, helperRel));
  for (const a of [
    ["init", "-q"],
    ["config", "user.email", "fx@example.invalid"],
    ["config", "user.name", "fx"],
    // Never inherit the operator's signing config: a fixture repo that spawns gpg turns
    // gpg-agent contention under parallel runners into scattered, unrelated-looking failures.
    ["config", "commit.gpgsign", "false"],
    ["config", "tag.gpgsign", "false"],
    ["add", "-A"],
    ["commit", "-q", "-m", "fixture"],
  ]) {
    execFileSync("git", ["-C", dir, ...a], { stdio: "ignore" });
  }
  return dir;
}

function run(dir, args) {
  const r = spawnSync("node", [path.join(dir, ".claude", "bin", "census-build.mjs"), "--manifest", "census-manifest.json", ...args], {
    cwd: dir,
    encoding: "utf8",
  });
  return { code: r.status, out: `${r.stdout || ""}${r.stderr || ""}` };
}

function commitAll(dir) {
  execFileSync("git", ["-C", dir, "add", "-A"], { stdio: "ignore" });
  execFileSync("git", ["-C", dir, "commit", "-q", "-m", "regen"], { stdio: "ignore" });
}

function want(actual, code, needle) {
  if (actual.code !== code) return `expected exit ${code}, got ${actual.code}: ${actual.out.slice(0, 300)}`;
  if (needle && !actual.out.includes(needle)) return `exit ${code} but output lacks '${needle}': ${actual.out.slice(0, 300)}`;
  return true;
}

// ── LEG 1 — a fresh block is CURRENT; a moved consumer floor is STALE ────────

check("L1-green: a freshly written block checks CURRENT (exit 0)", () => {
  const d = mkRepo(baseFiles());
  const w = run(d, ["--write"]);
  if (w.code !== 0) return `--write exited ${w.code}: ${w.out.slice(0, 300)}`;
  commitAll(d);
  return want(run(d, ["--check"]), 0, "is current");
});

check("L1-red: moving a real consumer's length floor reports STALE (exit 1)", () => {
  const d = mkRepo(baseFiles());
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  commitAll(d);
  const p = path.join(d, "consumer-live.mjs");
  fs.writeFileSync(p, fs.readFileSync(p, "utf8").replace("t.length >= 3", "t.length >= 9"));
  commitAll(d);
  return want(run(d, ["--check"]), 1, "STALE");
});

// ── LEG 2 — the freshness predicate answers WITHOUT deriving the census ─────

check("L2-green: the STALE verdict states it was reached without deriving", () => {
  const d = mkRepo(baseFiles());
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  commitAll(d);
  const p = path.join(d, "consumer-live.mjs");
  fs.writeFileSync(p, fs.readFileSync(p, "utf8").replace("t.length >= 3", "t.length >= 9"));
  commitAll(d);
  return want(run(d, ["--check"]), 1, "Determined without deriving the census");
});

check("L2-red: a hand-edited block whose inputs are UNMOVED is still caught (exit 1)", () => {
  const d = mkRepo(baseFiles());
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  commitAll(d);
  const p = path.join(d, "lib", "producer.mjs");
  // Edit a rendered COUNT inside the block. No input moved, so the digest still matches and
  // only the full text comparison can see it. If this passes, the digest is doing all the work
  // and the tamper case is uncovered.
  const before = fs.readFileSync(p, "utf8");
  const txt = before.replace(/RUNTIME CONSUMERS \((\d+)\)/, (_m, n) => `RUNTIME CONSUMERS (${Number(n) + 1})`);
  if (txt === before) return "the fixture's own edit did not apply — case is inert, not passing";
  fs.writeFileSync(p, txt);
  commitAll(d);
  return want(run(d, ["--check"]), 1, "HAND-EDITED");
});

// ── LEG 3 — the input set is DISCOVERED, not declared ───────────────────────

check("L3-green: a consumer the manifest never names APPEARS in the block", () => {
  const d = mkRepo(baseFiles({ "surprise.mjs": CONSUMER_DEAD.replace("orphanLane", "surpriseLane") }));
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  const txt = fs.readFileSync(path.join(d, "lib", "producer.mjs"), "utf8");
  return txt.includes("surprise.mjs") && txt.includes("surpriseLane")
    ? true
    : "the undeclared consumer is absent from the generated block";
});

check("L3-red: removing that consumer removes its row and reports STALE", () => {
  const d = mkRepo(baseFiles({ "surprise.mjs": CONSUMER_DEAD.replace("orphanLane", "surpriseLane") }));
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  commitAll(d);
  fs.rmSync(path.join(d, "surprise.mjs"));
  commitAll(d);
  const c = run(d, ["--check"]);
  if (c.code !== 1) return `expected STALE exit 1, got ${c.code}`;
  if (run(d, ["--write"]).code !== 0) return "regeneration failed";
  return fs.readFileSync(path.join(d, "lib", "producer.mjs"), "utf8").includes("surpriseLane")
    ? "the removed consumer is STILL in the regenerated block"
    : true;
});

// ── LEG 4 — dead code is DETECTED, not remembered ───────────────────────────

check("L4-red: a consumer function with no callers is reported DEAD CODE", () => {
  const d = mkRepo(baseFiles({ "consumer-dead.mjs": CONSUMER_DEAD }));
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  const txt = fs.readFileSync(path.join(d, "lib", "producer.mjs"), "utf8");
  const line = txt.split("\n").find((l) => l.includes("callers of orphanLane"));
  if (!line) return "no callers row for orphanLane";
  return line.includes("DEAD CODE") ? true : `orphanLane not reported dead: ${line.trim()}`;
});

check("L4-green: a consumer function WITH a caller is not reported dead", () => {
  const d = mkRepo(baseFiles({ "consumer-dead.mjs": CONSUMER_DEAD }));
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  const txt = fs.readFileSync(path.join(d, "lib", "producer.mjs"), "utf8");
  const line = txt.split("\n").find((l) => l.includes("callers of liveLane"));
  if (!line) return "no callers row for liveLane";
  return !line.includes("DEAD CODE") && /callers of liveLane: [1-9]/.test(line)
    ? true
    : `liveLane's caller count is wrong: ${line.trim()}`;
});

// ── LEG 5 — what it cannot determine is SAID, not guessed and not dropped ───

check("L5-red: an ambiguous function name yields UNDETERMINED, never a count", () => {
  // Two DIFFERENT functions share a name, so a name-keyed caller search cannot attribute a
  // call to either. A count here would be arithmetically real and answer a different question.
  const dup = [
    'import { deriveDynamicTokens } from "./lib/producer.mjs";',
    "export function twin(root) {",
    "  const { gate } = deriveDynamicTokens(root);",
    "  return gate;",
    "}",
    "",
  ].join("\n");
  const other = ["export function twin(x) {", "  return x;", "}", "export const USE = twin(1);", ""].join("\n");
  const d = mkRepo(baseFiles({ "twin-a.mjs": dup, "twin-b.mjs": other }));
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  const line = fs
    .readFileSync(path.join(d, "lib", "producer.mjs"), "utf8")
    .split("\n")
    .find((l) => l.includes("callers of twin"));
  if (!line) return "the ambiguous row was DROPPED — omission is the defect this leg exists for";
  return line.includes("UNDETERMINED") && line.includes("declared 2")
    ? true
    : `ambiguity not declared: ${line.trim()}`;
});

check("L5-green: an UNambiguous name still gets a real count, not UNDETERMINED", () => {
  const d = mkRepo(baseFiles());
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  const line = fs
    .readFileSync(path.join(d, "lib", "producer.mjs"), "utf8")
    .split("\n")
    .find((l) => l.includes("callers of liveLane"));
  return line && !line.includes("UNDETERMINED")
    ? true
    : `an unambiguous name was reported UNDETERMINED — the gate over-fires: ${line}`;
});

// ── LEG 6 — UNRUNNABLE (2) is distinguishable from STALE (1) ────────────────

check("L6-red: --write over an UNCOMMITTED consumer refuses with exit 2", () => {
  const d = mkRepo(baseFiles());
  fs.writeFileSync(path.join(d, "untracked-consumer.mjs"), CONSUMER_DEAD);
  return want(run(d, ["--write"]), 2, "UNRUNNABLE");
});

check("L6-green: --write over a clean tree writes and exits 0", () => {
  const d = mkRepo(baseFiles());
  return want(run(d, ["--write"]), 0, "wrote block into");
});

// ── LEG 7 — a missing marked region REFUSES rather than choosing a location ──

check("L7-red: a target with no markers refuses with exit 2 naming the marker", () => {
  const files = baseFiles();
  files["lib/producer.mjs"] = files["lib/producer.mjs"]
    .split("\n")
    .filter((l) => !l.includes("CENSUS:BEGIN") && !l.includes("CENSUS:END"))
    .join("\n");
  const d = mkRepo(files);
  return want(run(d, ["--write"]), 2, "CONSUMER-CENSUS");
});

check("L7-green: a target WITH markers writes between them and preserves the prose", () => {
  const d = mkRepo(baseFiles());
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  const txt = fs.readFileSync(path.join(d, "lib", "producer.mjs"), "utf8");
  return txt.includes("judgment prose that must survive regeneration untouched") &&
    txt.includes("// more judgment prose")
    ? true
    : "regeneration destroyed the hand-written prose around the block";
});

// ── LEG 8 — the return keys are READ from the producer, not declared ────────

check("L8-green: the block names the producer's ACTUAL return keys", () => {
  const d = mkRepo(baseFiles());
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  return fs.readFileSync(path.join(d, "lib", "producer.mjs"), "utf8").includes("{ scrub, gate, unhonoured }")
    ? true
    : "the derived key set does not match the producer's return statement";
});

check("L8-red: adding a fourth return key moves the block without a manifest edit", () => {
  const files = baseFiles();
  files["lib/producer.mjs"] = producer(["scrub", "gate", "unhonoured", "fourth"]).replace(
    "const scrub = [], gate = [], unhonoured = [];",
    "const scrub = [], gate = [], unhonoured = [], fourth = [];",
  );
  const d = mkRepo(files);
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  return fs.readFileSync(path.join(d, "lib", "producer.mjs"), "utf8").includes("fourth")
    ? true
    : "a new return key did not reach the block — the keys are being taken from somewhere else";
});

// ── LEG 9 — prose is not a call site ────────────────────────────────────────

check("L9-red: a file that only MENTIONS the symbol contributes no row", () => {
  const d = mkRepo(baseFiles());
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  const txt = fs.readFileSync(path.join(d, "lib", "producer.mjs"), "utf8");
  const rows = txt.split("\n").filter((l) => l.includes("mention-only.mjs:"));
  return rows.length === 0 ? true : `a prose mention was counted as a consumer: ${rows[0].trim()}`;
});

check("L9-green: the mention-only file is still SEEN as an input (it moves the digest)", () => {
  // The complement, and it is the one that stops L9-red passing vacuously: if the file were
  // simply invisible rather than correctly classified, editing it could not move the digest.
  const d = mkRepo(baseFiles());
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  commitAll(d);
  const p = path.join(d, "mention-only.mjs");
  fs.writeFileSync(p, `${fs.readFileSync(p, "utf8")}// deriveDynamicTokens again\n`);
  commitAll(d);
  return want(run(d, ["--check"]), 1, "STALE");
});

// ── LEG 10 — a broken search REFUSES rather than reporting a census of zero ──

check("L10-red: zero matches refuses with exit 2 rather than an empty census", () => {
  const files = baseFiles();
  const m = { ...MANIFEST, symbol: "aSymbolNoFileContains" };
  files["census-manifest.json"] = JSON.stringify(m, null, 2) + "\n";
  const d = mkRepo(files);
  return want(run(d, ["--write"]), 2, "search failure, not a census of zero");
});

check("L10-green: a symbol that IS present produces a census rather than refusing", () => {
  const d = mkRepo(baseFiles());
  return want(run(d, ["--write"]), 0, "wrote block into");
});

// ── LEG 11 — an UNDETERMINED occurrence is VISIBLE, never collapsed into a count ──
//
// Surfaced by THIS suite against the real corpus: a non-runtime file is summarised per FILE,
// and a bare count hid four UNDETERMINED occurrences that only `--json` could see. An unknown
// visible in one mode and absent from the durable artifact is an unknown the block omitted.

/** A non-runtime file whose symbol occurrences sit inside a multi-line string: the byte-level
 *  mask says "string", the independent line-shape classifier says "code". The generator must
 *  DECLARE the disagreement rather than pick a side. */
const AMBIGUOUS_NONRUNTIME = [
  "export const TEMPLATE = [",
  '  "export function fake(root) {",',
  '  "  const { gate } = deriveDynamicTokens(root);",',
  '  "  return gate;",',
  '  "}",',
  "].join(String.fromCharCode(10));",
  "",
].join("\n");

check("L11-red: an UNDETERMINED occurrence is named in the block, not collapsed into a count", () => {
  const d = mkRepo(baseFiles({ "fx-ambiguous.test.mjs": AMBIGUOUS_NONRUNTIME }));
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  const txt = fs.readFileSync(path.join(d, "lib", "producer.mjs"), "utf8");
  if (!txt.includes("UNDETERMINED OCCURRENCES")) {
    return "the block carries no UNDETERMINED section — the unknown was collapsed into a bare count";
  }
  return txt.includes("fx-ambiguous.test.mjs:3") && txt.includes("classifiers disagree")
    ? true
    : "the UNDETERMINED section does not name the occurrence or its reason";
});

check("L11-green: a corpus with no ambiguity carries NO UNDETERMINED section", () => {
  // The complement, and it is what stops L11-red passing vacuously: if the section were emitted
  // unconditionally, the red pole would pass against a generator that had determined nothing.
  const d = mkRepo(baseFiles());
  if (run(d, ["--write"]).code !== 0) return "--write failed";
  const txt = fs.readFileSync(path.join(d, "lib", "producer.mjs"), "utf8");
  return txt.includes("UNDETERMINED OCCURRENCES")
    ? "an UNDETERMINED section was emitted for a corpus with nothing undetermined — the signal is noise"
    : true;
});

// ── summary ─────────────────────────────────────────────────────────────────
console.log(`\nconsumer-census fixtures: ${pass} passed, ${failures.length} failed`);
if (failures.length) {
  console.log(`FAILED: ${failures.join(", ")}`);
  process.exit(1);
}
